version: '3.8'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  uday:
    build: .
    depends_on:
      - db
    ports:
      - "5000:5000"
    env_file:
      - .env
    command: ["./wait-for-it.sh", "db:5432", "--", "python", "app/app.py"]

volumes:
  pgdata: