apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: uday-gateway
  namespace: uday-app
spec:
  gatewayClassName: istio
  listeners:
    - name: http
      protocol: HTTP
      port: 80