namespace: uday-app
istioInjection:
  enabled: "enabled"


postgres:
  user: postgres
  password: postgres
  db: udaydb
  pvcSize: 5Gi
  image: postgres:16

app:
  image: udaytc/uday-app:v2
  servicePort: 80
  containerPort: 5000
  hostname: uday-app.uday.com.br

livenessProbe:
  path: /healthz
  port: 8080
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3

readinessProbe:
  path: /healthz
  port: 8080
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 2
  failureThreshold: 3
