apiVersion: v1
kind: Service
metadata:
  name: uday-app-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: uday
  ports:
    - port: {{ .Values.app.servicePort }}
      targetPort: {{ .Values.app.containerPort }}
      protocol: TCP
